name: boostnote
version: "0.9.0"
summary: A note-taking app for programmers
description: |
  Boostnote is an open source note-taking app made for programmers just like you. https://boostnote.io
  https://github.com/BoostIO/Boostnote

grade: stable
confinement: strict

apps:
  pats-boostnote:
    command: desktop-launch $SNAP/dist/Boostnote-linux-x64/Boostnote
    desktop: dist/boostnote.desktop
    plugs:
     - browser-support
     - network
     - unity7
     - gsettings

parts:
  boostnote:
    plugin: grunt
    source: .
    gruntfile: gruntfile-snap.js
    # filesets: copy the dist/ dir created from 'build' into the stage and prime parts
    filesets:
      dist: [dist/*]
    build-packages:
      - execstack
    after: [desktop-glib-only]
    stage-packages:
      - libappindicator1
      - libdbusmenu-glib4
      - libgcrypt-dev
      - liblzma-dev
      - libgpg-error-dev
      - libsystemd-dev
      - libnotify4
      - libunity9
      - libgconf-2-4
      - libnss3
      - libxss1
      - fontconfig-config
      - libx11-xcb-dev
      - zlib1g-dev
      - libxtst-dev
      - libasound-dev
      - libmount-dev
      - libpcre++-dev
      - libselinux1-dev
      - libc6